### ISSUE TITLE
Support for Visual Studio 2012

### ISSUE THREAD

**Issue by ghost** [EbenZhang/VbSharpOutliner#5]
Hello EbenZhang:

I like you VbSharpOutliner extension, can you advise how to make it supports Visual Studio 2012?

Thank you,

Tuyen Nguyen

**Comment by EbenZhang** [comment]
Unfortunately, vs2012 is not supported because this plugin is based on Roslyn of VS2015. But you could use this one instead: https://marketplace.visualstudio.com/items?itemName=Skybladev2.Coutline2012.
